# Generated by Django 4.1.5 on 2023-11-22 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storages', '0003_alter_storage_name'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='passport_image',
            field=models.ImageField(null=True, upload_to='passport-image'),
        ),
        migrations.CreateModel(
            name='ClientId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.client')),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storages.storage')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='client_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.clientid'),
        ),
    ]
