# Generated by Django 4.1.5 on 2023-11-22 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_clientid_id_str_alter_client_passport_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
