# Generated by Django 4.1.5 on 2023-11-22 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_client_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientid',
            name='selected_client',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selected_client', to='users.client'),
        ),
    ]
