# Generated by Django 4.1.5 on 2023-11-22 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_clientid_selected_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientid',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
