# Generated by Django 4.1.5 on 2023-11-22 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_clientid_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientid',
            name='selected_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selected_client', to='users.client'),
        ),
    ]
