# Generated by Django 4.1.5 on 2023-11-22 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_info_alter_text_lang'),
        ('storages', '0003_alter_storage_name'),
        ('users', '0011_alter_clientid_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='clientid',
            unique_together={('storage', 'selected_client', 'user')},
        ),
    ]
