# Generated by Django 4.1.5 on 2023-11-22 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storages', '0003_alter_storage_name'),
        ('users', '0012_alter_clientid_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='clientid',
            unique_together={('storage', 'selected_client')},
        ),
    ]
