# Generated by Django 4.1.5 on 2023-11-22 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_info_alter_text_lang'),
        ('storages', '0003_alter_storage_name'),
        ('users', '0013_alter_clientid_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='clientid',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='clientid',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.user'),
        ),
        migrations.AlterUniqueTogether(
            name='clientid',
            unique_together={('storage', 'selected_client', 'user')},
        ),
    ]
