# Generated by Django 4.1.5 on 2023-11-24 03:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('storages', '0005_alter_storagetranslation_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bot', '0003_infotranslation_delete_text_remove_info_slug_and_more'),
        ('users', '0014_alter_clientid_unique_together_alter_clientid_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalClientId',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('id_str', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('selected_client', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.client')),
                ('storage', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='storages.storage')),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='bot.user')),
            ],
            options={
                'verbose_name': 'historical client id',
                'verbose_name_plural': 'historical client ids',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
