# Generated by Django 4.1.5 on 2023-11-24 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storages', '0006_alter_image_options_alter_storage_options_and_more'),
        ('bot', '0004_alter_info_options_alter_infotranslation_options_and_more'),
        ('users', '0015_historicalclientid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Паспорт клиента', 'verbose_name_plural': 'Паспорта клиентов'},
        ),
        migrations.AlterModelOptions(
            name='clientid',
            options={'verbose_name': 'ИД клиента', 'verbose_name_plural': 'ИД клиентов'},
        ),
        migrations.AlterModelOptions(
            name='historicalclientid',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical ИД клиента', 'verbose_name_plural': 'historical ИД клиентов'},
        ),
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.CharField(max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='client',
            name='fio',
            field=models.CharField(max_length=255, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='client',
            name='passport',
            field=models.CharField(max_length=255, unique=True, verbose_name='Паспорт серия и номер'),
        ),
        migrations.AlterField(
            model_name='client',
            name='passport_image',
            field=models.ImageField(null=True, upload_to='passport-image', verbose_name='Паспорт фото'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=255, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='client',
            name='pnfl',
            field=models.CharField(max_length=255, unique=True, verbose_name='ПИНФЛ'),
        ),
        migrations.AlterField(
            model_name='clientid',
            name='clients',
            field=models.ManyToManyField(to='users.client', verbose_name='Поспорта клиентов'),
        ),
        migrations.AlterField(
            model_name='clientid',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='Не автивный'),
        ),
        migrations.AlterField(
            model_name='clientid',
            name='id_str',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='ИД'),
        ),
        migrations.AlterField(
            model_name='clientid',
            name='selected_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selected_client', to='users.client', verbose_name='Выбранный клиент'),
        ),
        migrations.AlterField(
            model_name='clientid',
            name='storage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storages.storage', verbose_name='Склад'),
        ),
        migrations.AlterField(
            model_name='clientid',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.user', verbose_name='Телеграм пользователь'),
        ),
        migrations.AlterField(
            model_name='historicalclientid',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='Не автивный'),
        ),
        migrations.AlterField(
            model_name='historicalclientid',
            name='id_str',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='ИД'),
        ),
        migrations.AlterField(
            model_name='historicalclientid',
            name='selected_client',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.client', verbose_name='Выбранный клиент'),
        ),
        migrations.AlterField(
            model_name='historicalclientid',
            name='storage',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='storages.storage', verbose_name='Склад'),
        ),
        migrations.AlterField(
            model_name='historicalclientid',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='bot.user', verbose_name='Телеграм пользователь'),
        ),
    ]
