# Generated by Django 4.1.5 on 2023-11-27 16:00

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_client_options_alter_clientid_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='create_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientid',
            name='create_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalclientid',
            name='create_date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 11, 27, 16, 0, 0, 458309, tzinfo=datetime.timezone.utc), editable=False),
            preserve_default=False,
        ),
    ]
