# Generated by Django 4.1.5 on 2023-11-30 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
