# Generated by Django 4.1.5 on 2023-11-30 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storages', '0014_alter_category_options_and_more'),
        ('users', '0019_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storages', models.ManyToManyField(to='storages.storage')),
            ],
        ),
    ]
