# Generated by Django 4.1.5 on 2023-11-30 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_usersettings_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersettings',
            options={'verbose_name': 'Настройка', 'verbose_name_plural': 'Настройки'},
        ),
    ]
