version: '3.3'

services:
  bot:
    container_name: onson-bot
    build:
      dockerfile: Dockerfile.bot
      context: .
    working_dir: "/app/"
    volumes:
      - .:/app/
    command: python manage.py runbot
    restart: always
    depends_on:
      - web
    env_file: .env

  web:
    container_name: onson-web
    build:
      dockerfile: Dockerfile.web
      context: .
    working_dir: "/app/"
    volumes:
      - .:/app/
    command: python manage.py runserver 0.0.0.0:7000
    ports:
      - "7000:7000"
    restart: always
    env_file: .env

  redis:
    container_name: onson-redis
    image: redis:7.2-rc3-alpine
    restart: always
    env_file:
      - .env
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    expose:
      - ${REDIS_PORT}
    volumes:
      - ./redis_data:/data

  front:
      container_name: onson-front
      build:
        context: ./front
        dockerfile: Dockerfile.front
      ports:
        - "3000:3000"
      command: sh -c "npm run preview"
      restart: always
      env_file:
        - ./.env
      volumes:
        - ./front/:/app/