# Generated by Django 4.1.5 on 2023-11-19 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
