# Generated by Django 4.1.5 on 2023-11-19 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storages', '0002_storage_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
