# Generated by Django 4.1.5 on 2023-11-23 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storages', '0004_remove_storage_address_remove_storage_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storagetranslation',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='storagetranslation',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
