# Generated by Django 4.1.5 on 2023-11-24 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storages', '0005_alter_storagetranslation_address_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'Фото склада', 'verbose_name_plural': 'Фотки склада'},
        ),
        migrations.AlterModelOptions(
            name='storage',
            options={'verbose_name': 'Склад', 'verbose_name_plural': 'Склади'},
        ),
        migrations.AlterModelOptions(
            name='storagetranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Склад Translation'},
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='image',
            name='storage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storages.storage', verbose_name='Склад'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Актив'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='phone',
            field=models.CharField(max_length=255, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Ключовая слова'),
        ),
        migrations.AlterField(
            model_name='storagetranslation',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='storagetranslation',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='storagetranslation',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст'),
        ),
    ]
