# Generated by Django 4.1.5 on 2023-11-25 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storages', '0006_alter_image_options_alter_storage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='per_price',
            field=models.FloatField(default=5.5),
        ),
    ]
