# Generated by Django 4.1.5 on 2023-11-28 05:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('storages', '0008_category_product_producttocart_producttranslation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producttranslation',
            name='desc',
            field=models.TextField(null=True),
        ),
    ]
