# Generated by Django 4.1.5 on 2023-12-01 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storages', '0014_alter_category_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttranslation',
            name='desc',
        ),
    ]
