# Generated by Django 4.1.5 on 2023-12-11 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storages', '0016_product_buyer_price_product_transfer_fee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='storage',
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='storages.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='storage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='storages.storage'),
        ),
        migrations.AlterField(
            model_name='product',
            name='transfer_fee',
            field=models.FloatField(null=True, verbose_name='Комиссия за перевод (%)'),
        ),
        migrations.DeleteModel(
            name='ProductTranslation',
        ),
    ]
