# Generated by Django 4.1.5 on 2023-12-11 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storages', '0018_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='storages.category', verbose_name='Радительская категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='storage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='storages.storage', verbose_name='Склад'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='has_online_buy',
            field=models.BooleanField(default=False, verbose_name='Есть онлайн магазин'),
        ),
    ]
