# Generated by Django 4.1.5 on 2023-12-14 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storages', '0021_alter_storage_my_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='my_order',
            field=models.IntegerField(default=0),
        ),
    ]
