# Generated by Django 4.1.5 on 2023-11-19 12:15
import parler
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('file', models.FileField(upload_to='info')),
                ('is_active', models.BooleanField(default=True)),
            ],
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.AlterField(
            model_name='text',
            name='lang',
            field=models.CharField(choices=[('ru', 'Русский'), ('uz', "O'zbekcha"), ('uz_cl', 'Узбекча')], max_length=20),
        ),
    ]
