# Generated by Django 4.1.5 on 2023-11-23 07:10

import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_info_alter_text_lang'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=255, null=True)),
                ('text', models.TextField(null=True)),
            ],
            options={
                'verbose_name': 'info Translation',
                'db_table': 'bot_info_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.DeleteModel(
            name='Text',
        ),
        migrations.RemoveField(
            model_name='info',
            name='slug',
        ),
        migrations.AlterField(
            model_name='user',
            name='lang',
            field=models.CharField(choices=[('ru', 'Русский'), ('uz', "O'zbekcha"), ('uz-cl', 'Узбекча')], default='uz', max_length=20),
        ),
        migrations.AddField(
            model_name='infotranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='bot.info'),
        ),
        migrations.AlterUniqueTogether(
            name='infotranslation',
            unique_together={('language_code', 'master')},
        ),
    ]
