# Generated by Django 4.1.5 on 2023-11-25 10:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_alter_info_options_alter_infotranslation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='last_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
