# Generated by Django 4.1.5 on 2023-12-04 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_faq_answer_image_faq_image_alter_faq_answer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='active',
        ),
        migrations.AddField(
            model_name='faq',
            name='message_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='not_active',
            field=models.BooleanField(default=False),
        ),
    ]
