# Generated by Django 4.1.5 on 2023-12-07 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_remove_faq_active_faq_message_id_faq_not_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='id',
            field=models.BigIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='username',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
