# Generated by Django 4.1.5 on 2023-12-11 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bot', '0010_alter_historicaluser_id_alter_user_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.TextField(null=True, verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer_image',
            field=models.ImageField(blank=True, null=True, upload_to='faq_answer', verbose_name='Фото ответа'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ответил'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='faq', verbose_name='Фото вапроса'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='not_active',
            field=models.BooleanField(default=False, verbose_name='Ответено'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='text',
            field=models.TextField(verbose_name='Вапрос'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='type',
            field=models.CharField(choices=[('faq_type_bot', 'Botda nosozlik'), ('faq_type_delivery', 'Yetkazib berishda nosozlik')], max_length=255, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.user', verbose_name='Владелец вопроса'),
        ),
    ]
