# Generated by Django 4.1.5 on 2023-12-13 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0011_alter_faq_options_alter_faq_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='info',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='info', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='infotranslation',
            name='title',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Загаловка'),
        ),
    ]
