# Generated by Django 4.1.5 on 2023-12-18 12:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0013_faq_storage_info_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
