# Generated by Django 4.1.5 on 2023-12-26 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0014_faq_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.TextField(blank=True, null=True, verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='create_date',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Дата создание'),
        ),
        migrations.AlterField(
            model_name='user',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создание'),
        ),
    ]
