# Generated by Django 4.1.5 on 2023-12-26 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0015_alter_faq_answer_alter_historicaluser_create_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='message_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
