# Generated by Django 4.1.5 on 2023-11-23 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0014_alter_clientid_unique_together_alter_clientid_user_and_more'),
        ('storages', '0005_alter_storagetranslation_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storages.storage')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('clientid', models.CharField(max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
                ('weight', models.FloatField()),
                ('facture_price', models.FloatField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.client', to_field='pnfl')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.part')),
            ],
        ),
    ]
