# Generated by Django 4.1.5 on 2023-11-23 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='status',
            field=models.CharField(choices=[('in_storage', 'В складе'), ('in_delivery', 'Доставка'), ('done', 'Доставлено')], default='in_storage', max_length=50),
        ),
    ]
