# Generated by Django 4.1.5 on 2023-11-24 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storages', '0006_alter_image_options_alter_storage_options_and_more'),
        ('users', '0016_alter_client_options_alter_clientid_options_and_more'),
        ('orders', '0004_historicalpart_historicalorder'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalorder',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Заказ', 'verbose_name_plural': 'historical Закази'},
        ),
        migrations.AlterModelOptions(
            name='historicalpart',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Партия', 'verbose_name_plural': 'historical Партии'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Закази'},
        ),
        migrations.AlterModelOptions(
            name='part',
            options={'verbose_name': 'Партия', 'verbose_name_plural': 'Партии'},
        ),
        migrations.AlterField(
            model_name='historicalorder',
            name='client',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.client', to_field='pnfl', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='historicalorder',
            name='clientid',
            field=models.CharField(max_length=255, null=True, verbose_name='Клиент ИД'),
        ),
        migrations.AlterField(
            model_name='historicalorder',
            name='date',
            field=models.DateField(null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='historicalorder',
            name='facture_price',
            field=models.FloatField(verbose_name='Счет-актура'),
        ),
        migrations.AlterField(
            model_name='historicalorder',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='historicalorder',
            name='number',
            field=models.IntegerField(verbose_name='Номер заказа'),
        ),
        migrations.AlterField(
            model_name='historicalorder',
            name='part',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='orders.part', verbose_name='Партия'),
        ),
        migrations.AlterField(
            model_name='historicalorder',
            name='weight',
            field=models.FloatField(verbose_name='Вес'),
        ),
        migrations.AlterField(
            model_name='historicalpart',
            name='number',
            field=models.IntegerField(db_index=True, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='historicalpart',
            name='status',
            field=models.CharField(choices=[('in_storage', 'В складе'), ('in_delivery', 'Доставка'), ('done', 'Доставлено')], default='in_storage', max_length=50, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='historicalpart',
            name='storage',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='storages.storage', verbose_name='Склад'),
        ),
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.client', to_field='pnfl', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='order',
            name='clientid',
            field=models.CharField(max_length=255, null=True, verbose_name='Клиент ИД'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='order',
            name='facture_price',
            field=models.FloatField(verbose_name='Счет-актура'),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='order',
            name='number',
            field=models.IntegerField(verbose_name='Номер заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.part', verbose_name='Партия'),
        ),
        migrations.AlterField(
            model_name='order',
            name='weight',
            field=models.FloatField(verbose_name='Вес'),
        ),
        migrations.AlterField(
            model_name='part',
            name='number',
            field=models.IntegerField(unique=True, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='part',
            name='status',
            field=models.CharField(choices=[('in_storage', 'В складе'), ('in_delivery', 'Доставка'), ('done', 'Доставлено')], default='in_storage', max_length=50, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='part',
            name='storage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storages.storage', verbose_name='Склад'),
        ),
    ]
