# Generated by Django 4.1.5 on 2023-11-25 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_historicalorder_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalorder',
            name='number',
            field=models.IntegerField(db_index=True, verbose_name='Номер заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='number',
            field=models.IntegerField(unique=True, verbose_name='Номер заказа'),
        ),
    ]
