# Generated by Django 4.1.5 on 2023-11-28 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_client_create_date_clientid_create_date_and_more'),
        ('orders', '0007_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='clientid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.clientid'),
        ),
    ]
