# Generated by Django 4.1.5 on 2023-11-30 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_client_create_date_clientid_create_date_and_more'),
        ('orders', '0009_report'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Карзина клиента', 'verbose_name_plural': 'Карзина клиента'},
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'verbose_name': 'Фото отчет', 'verbose_name_plural': 'Фото отчеты'},
        ),
        migrations.AlterField(
            model_name='cart',
            name='clientid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.clientid', verbose_name='Клиент ИД'),
        ),
        migrations.AlterField(
            model_name='report',
            name='clientid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.clientid', verbose_name='Клиент ИД'),
        ),
        migrations.AlterField(
            model_name='report',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата и время'),
        ),
        migrations.AlterField(
            model_name='report',
            name='image',
            field=models.ImageField(upload_to='report', verbose_name='Фото'),
        ),
    ]
