# Generated by Django 4.1.5 on 2023-11-30 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_part_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpart',
            name='number',
            field=models.IntegerField(verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='part',
            name='number',
            field=models.IntegerField(verbose_name='Номер'),
        ),
    ]
