# Generated by Django 4.1.5 on 2023-12-01 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_alter_historicalpart_number_alter_part_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorder',
            name='products',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='historicalorder',
            name='with_online_buy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='order',
            name='with_online_buy',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='historicalorder',
            name='number',
            field=models.IntegerField(null=True, verbose_name='Номер заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='number',
            field=models.IntegerField(null=True, verbose_name='Номер заказа'),
        ),
    ]
