# Generated by Django 4.1.5 on 2023-12-01 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_historicalorder_products_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='part',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.part'),
        ),
    ]
