# Generated by Django 4.1.5 on 2023-12-11 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_cart_part'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalorder',
            name='with_online_buy',
            field=models.BooleanField(default=False, verbose_name='С онлайн магазина'),
        ),
        migrations.AlterField(
            model_name='order',
            name='with_online_buy',
            field=models.BooleanField(default=False, verbose_name='С онлайн магазина'),
        ),
    ]
