# Generated by Django 4.1.5 on 2023-12-12 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_alter_historicalorder_with_online_buy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='report')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.report')),
            ],
        ),
        migrations.RemoveField(
            model_name='report',
            name='image',
        ),
    ]
