# Generated by Django 4.1.5 on 2023-12-18 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_alter_reportimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpart',
            name='status',
            field=models.CharField(choices=[('in_first', 'В аэропорту отправителя'), ('in_second', 'В аэропорту принимателя'), ('in_customs', 'в Таможенном процессе'), ('in_delivery', 'в доставке')], default='in_first', max_length=50, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='part',
            name='status',
            field=models.CharField(choices=[('in_first', 'В аэропорту отправителя'), ('in_second', 'В аэропорту принимателя'), ('in_customs', 'в Таможенном процессе'), ('in_delivery', 'в доставке')], default='in_first', max_length=50, verbose_name='Статус'),
        ),
    ]
